package com.hdfs.file.bean;

// Generated 2011-3-16 15:10:21 by Hibernate Tools 3.4.0.CR1

/**
 * HdfsFilesystem generated by hbm2java
 */
public class HdfsFilesystem implements java.io.Serializable {

	private int fsId;
	private String fsUrl;
	private String fsName;

	public HdfsFilesystem() {
	}

	public HdfsFilesystem(int fsId, String fsUrl, String fsName) {
		this.fsId = fsId;
		this.fsUrl = fsUrl;
		this.fsName = fsName;
	}

	public int getFsId() {
		return this.fsId;
	}

	public void setFsId(int fsId) {
		this.fsId = fsId;
	}

	public String getFsUrl() {
		return this.fsUrl;
	}

	public void setFsUrl(String fsUrl) {
		this.fsUrl = fsUrl;
	}

	public String getFsName() {
		return this.fsName;
	}

	public void setFsName(String fsName) {
		this.fsName = fsName;
	}

}
