package com.hdfs.file.bean;

// Generated 2011-3-16 15:10:21 by Hibernate Tools 3.4.0.CR1

/**
 * HdfsMemory generated by hbm2java
 */
public class HdfsMemory implements java.io.Serializable {

	private Integer memoryId;
	private int priority;
	private int totalmemory;
	private int memoryused;

	public HdfsMemory() {
	}

	public HdfsMemory(int priority, int totalmemory, int memoryused) {
		this.priority = priority;
		this.totalmemory = totalmemory;
		this.memoryused = memoryused;
	}

	public Integer getMemoryId() {
		return this.memoryId;
	}

	public void setMemoryId(Integer memoryId) {
		this.memoryId = memoryId;
	}

	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public int getTotalmemory() {
		return this.totalmemory;
	}

	public void setTotalmemory(int totalmemory) {
		this.totalmemory = totalmemory;
	}

	public int getMemoryused() {
		return this.memoryused;
	}

	public void setMemoryused(int memoryused) {
		this.memoryused = memoryused;
	}

}
