package com.hdfs.file.bean;

// Generated 2011-3-16 15:10:21 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Long userId;
	private String username;
	private String password;
	private String email;
	private String phone;
	private Integer memoryId;
	private Integer active;
	private String rootDirectory;
	private Integer checkuser;

	public Users() {
	}

	public Users(String username, String password, String email, String phone,
			Integer memoryId, Integer active, String rootDirectory,Integer checkuser) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.phone = phone;
		this.memoryId = memoryId;
		this.active = active;
		this.rootDirectory = rootDirectory;
		this.checkuser=checkuser;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getMemoryId() {
		return this.memoryId;
	}

	public void setMemoryId(Integer memoryId) {
		this.memoryId = memoryId;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	public String getRootDirectory() {
		return this.rootDirectory;
	}

	public void setRootDirectory(String rootDirectory) {
		this.rootDirectory = rootDirectory;
	}
	
	public Integer getCheckUser(){
		return this.checkuser;
	}
	
	public void setCheckuser(Integer checkuser) {
		this.checkuser = checkuser;
	}


}
